### ISSUE TITLE
Duvidas sobre a estrutura do site

### ISSUE THREAD

**Issue by humrochagf** [flask-brasil/flaskconf-site#3]
Opa, beleza?

Eu sou o Humberto da APyB, queria tirar uma dúvida sobre a estrutura do site.

Vocês já tem uma branch onde vai ficar o html estático do site? Que aí eu consigo subir a infra de deploy automático da APyB pros subdomínios todos apontarem corretamente e para subirmos o https no site.

Na minha primeira tentativa vi que tava em jekyll e daí o ghpages não gerava os arquivos estáticos, mas parece que agora a estrutura mudou

**Comment by filipecifali** [comment]
Vai ser no master mesmo, ainda vamos limpar o repo :+1:
